version: "3"
services:
    couchbase:
        build: couchbase
        container_name: couchbase-name-1
        volumes:
          - ./couchbase_mount:/opt/couchbase/var/lib/couchbase/data
        ports:
          - 8091:8091
          - 8092:8092
          - 8093:8093
          - 11210:11210
        environment:
          - COUCHBASE_ADMINISTRATOR_USERNAME=${COUCHBASE_ADMINISTRATOR_USERNAME}
          - COUCHBASE_ADMINISTRATOR_PASSWORD=${COUCHBASE_ADMINISTRATOR_PASSWORD}
          - COUCHBASE_BUCKET=${COUCHBASE_BUCKET}
    mongo:
        build: mongo
        container_name: mongo-name-1
        environment:
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
          - APP_MONGO_HOST=${MONGO_HOST}
          - MONGO_PORT=${MONGO_PORT}
          - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
          - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
          - APP_MONGO_USER=${APP_MONGO_USER}
          - APP_MONGO_PASS=${APP_MONGO_PASS}
          - APP_MONGO_DB=${APP_MONGO_DB}
        volumes:
          - ./mongo_mount:/data/db
        ports:
            - 27017:27017